### ISSUE TITLE
I tried to push and it rejected

### ISSUE THREAD

**Issue by timfam** [orionjs/documentation#1]
You were suppose to be resting and I was suppose to complete the documentation left :) Oh well we both  just did same task

**Comment by nicolaslopezj** [comment]
Sorry I can't contain myself. I only did the easy ones.

**Comment by timfam** [comment]
hehehe I will pull it down afresh tomorrow and add more. You Amigo
need to get some beautiful sleep

**Comment by timfam** [comment]
I reverted the commit this should have solved problem. I can revert further, should I ?

**Comment by timfam** [comment]
I see the problem damn my bad fixing now

**Comment by timfam** [comment]
Fixed that , but grounddb is caching it whish is great. so check it out on another browser
