### ISSUE TITLE
Please make documentation clearer

### ISSUE THREAD

**Issue by ffxsam** [orionjs/documentation#33]
Hey guys,

Great job on Orion! My only quibble is that the documentation isn't very clear about where certain code belongs (client, server, or both). For instance:

```javascript
orion.dictionary.addDefinition('description', 'site', {
    type: String,
    label: "Description"
});
```

Through trial and error, I figured out this belongs in the lib folder.

Throughout the documentation, I would specify whether certain code belongs on the server, client, or both. And if it needs to go in lib, that should be indicated as well.

**Comment by timfam** [comment]
Hey Sam,
Agreed and we do accept PRs for docs so please feel free to help fix these many pains. We also have  examples that shows are to use Orion.

**Comment by ffxsam** [comment]
Excellent. I'll contribute when I have some time!
